'use client';

import { useEffect, useMemo, useState } from 'react';

type Staff = Record<string, any>;
type Candidate = Record<string, any>;

type Filter = 'all' | 'recruitment' | 'internal';

export default function AdminStaffPage(){
 const [staff,setStaff]=useState<Staff[]>([]);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [filter,setFilter]=useState<Filter>('all');const [error,setError]=useState('');const [activation,setActivation]=useState('');
 const [pickerOpen,setPickerOpen]=useState(false);const [candidates,setCandidates]=useState<Candidate[]>([]);const [candidateSearch,setCandidateSearch]=useState('');const [candidateBusy,setCandidateBusy]=useState(false);const [promotingId,setPromotingId]=useState('');
 async function load(){const r=await fetch(`/api/admin/staff?${new URLSearchParams({...(search?{search}:{}),...(status?{status}:{})})}`,{cache:'no-store'});const d=await r.json();if(r.status===401){setError('Admin session required.');return}if(!r.ok){setError(d.error||'Unable to load staff.');return}setStaff(d.staff||[])}
 useEffect(()=>{void load()},[status]);
 async function openPicker(){setPickerOpen(true);setError('');setCandidateBusy(true);try{const r=await fetch('/api/admin/staff?mode=promotion_candidates',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load recruitment intakes.');setCandidates(d.candidates||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load recruitment intakes.')}finally{setCandidateBusy(false)}}
 async function promote(applicationId:string){setPromotingId(applicationId);setError('');try{const r=await fetch('/api/admin/staff',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'promote',applicationId})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to create staff identity.');setPickerOpen(false);setActivation(d.activationUrl||'');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create staff identity.')}finally{setPromotingId('')}}
 async function copy(){if(activation)await navigator.clipboard.writeText(activation)}
 const filtered=useMemo(()=>staff.filter((s)=>{const source=s.application_id?'recruitment':'internal';return (filter==='all'||(filter==='recruitment'&&source==='recruitment')||(filter==='internal'&&source==='internal'))}),[staff,filter]);
 const visibleCandidates=useMemo(()=>candidates.filter((c)=>!c.already_staff&&(!candidateSearch.trim()||`${c.full_name} ${c.email} ${c.role_applied} ${c.status}`.toLowerCase().includes(candidateSearch.toLowerCase()))),[candidates,candidateSearch]);
 return <main style={{padding:'32px 5vw',background:'#f7f9fc',minHeight:'100vh',fontFamily:'system-ui',color:'#102a43'}}><div style={{maxWidth:1320,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:20,marginBottom:10}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1.4,color:'#0f766e'}}>BIMED Healthcare</div><h1 style={{margin:'5px 0'}}>Workforce Staff</h1><p style={{margin:0,color:'#627d98'}}>One permanent BIMED workforce directory. BIMED IDs are generated automatically.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={()=>void openPicker()} style={{padding:'11px 15px',border:0,borderRadius:10,background:'#0f766e',color:'#fff',fontWeight:800}}>Add recruitment intake</button><a href='/admin/staff/new' style={{padding:'11px 15px',border:'1px solid #d9e2ec',borderRadius:10,background:'#fff',color:'#334e68',fontWeight:800,textDecoration:'none'}}>Create internal staff</a><a href='/admin/rota' style={{padding:'11px 15px',border:'1px solid #d9e2ec',borderRadius:10,background:'#fff',color:'#334e68',textDecoration:'none',fontWeight:800}}>Rota manager</a><a href='/admin/messages' style={{padding:'11px 15px',border:'1px solid #d9e2ec',borderRadius:10,background:'#fff',color:'#334e68',textDecoration:'none',fontWeight:800}}>BIMED Messages</a></div></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:12,margin:'0 0 18px'}}><div style={{padding:14,borderRadius:12,background:'#e6fffb',border:'1px solid #b7eee6'}}><strong>Recruitment intake</strong><div style={{fontSize:12,color:'#486581',marginTop:4}}>Created by promoting an employment-ready candidate. Their recruitment record remains linked.</div></div><div style={{padding:14,borderRadius:12,background:'#fff',border:'1px solid #e5eaf0'}}><strong>Internal BIMED staff</strong><div style={{fontSize:12,color:'#486581',marginTop:4}}>Administration, HR, finance, recruitment, operations and management. Not care or clinical intake roles.</div></div><div style={{padding:14,borderRadius:12,background:'#fff',border:'1px solid #e5eaf0'}}><strong>Identity</strong><div style={{fontSize:12,color:'#486581',marginTop:4}}>No manual BIMED ID entry. The system generates the permanent ID automatically.</div></div></div>
 {activation&&<div style={{background:'#ecfdf5',border:'1px solid #a7f3d0',padding:14,borderRadius:12,marginBottom:18}}><strong>Activation link generated.</strong><div style={{fontSize:13,marginTop:6,wordBreak:'break-all'}}>{activation}</div><button onClick={copy} style={{marginTop:8,padding:'8px 10px',border:'1px solid #a7f3d0',background:'#fff',borderRadius:8}}>Copy link</button></div>}{error&&<div style={{color:'#9b2c2c',background:'#fff5f5',padding:12,borderRadius:10,marginBottom:18}}>{error}</div>}
 <div style={{display:'flex',gap:10,marginBottom:15,flexWrap:'wrap'}}><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder='Search name, email or BIMED ID' style={{flex:1,minWidth:260,padding:12,border:'1px solid #d9e2ec',borderRadius:10}}/><select value={filter} onChange={e=>setFilter(e.target.value as Filter)} style={{padding:12,border:'1px solid #d9e2ec',borderRadius:10}}><option value='all'>All staff</option><option value='recruitment'>Recruitment intake</option><option value='internal'>Internal BIMED staff</option></select><select value={status} onChange={e=>setStatus(e.target.value)} style={{padding:12,border:'1px solid #d9e2ec',borderRadius:10}}><option value=''>All statuses</option><option value='pre_arrival'>Pre-arrival</option><option value='active'>Active</option><option value='on_leave'>On leave</option><option value='suspended'>Suspended</option><option value='former'>Former</option></select><button onClick={()=>void load()} style={{padding:'11px 15px',border:'1px solid #d9e2ec',borderRadius:10,background:'#fff'}}>Search</button></div>
 <div style={{background:'#fff',border:'1px solid #e5eaf0',borderRadius:16,overflow:'hidden'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr style={{background:'#f8fafc'}}>{['Source','BIMED ID','Staff','Role','Status','Start date','PPS','Photo',''].map(h=><th key={h} style={{padding:12,textAlign:'left',fontSize:12,color:'#627d98'}}>{h}</th>)}</tr></thead><tbody>{filtered.map(s=><tr key={s.id} style={{borderTop:'1px solid #edf2f7'}}><td style={{padding:12}}><span style={{padding:'5px 8px',borderRadius:999,background:s.application_id?'#e6fffb':'#f4f7fb',color:s.application_id?'#0f766e':'#334e68',fontSize:11,fontWeight:900}}>{s.application_id?'Recruitment intake':'Internal staff'}</span></td><td style={{padding:12,fontWeight:900}}>{s.bimed_id}</td><td style={{padding:12}}><div style={{fontWeight:800}}>{s.full_name}</div><div style={{fontSize:12,color:'#627d98'}}>{s.email}</div>{s.portal_address&&<div style={{fontSize:11,color:'#829ab1',marginTop:3}}>{s.portal_address}</div>}</td><td style={{padding:12}}>{s.role||s.job_title||'—'}</td><td style={{padding:12}}>{s.status}</td><td style={{padding:12}}>{s.employment_start_date||'—'}</td><td style={{padding:12}}>{s.pps_number?'Provided':'Pending'}</td><td style={{padding:12}}>{s.profile_photo_path?'Uploaded':'Not uploaded'}</td><td style={{padding:12}}><a href={`/admin/staff/${s.id}`} style={{padding:'7px 10px',border:'1px solid #d9e2ec',borderRadius:8,textDecoration:'none',color:'#334e68',fontWeight:700}}>View</a></td></tr>)}{filtered.length===0&&<tr><td colSpan={9} style={{padding:30,textAlign:'center',color:'#627d98'}}>No staff records found.</td></tr>}</tbody></table></div>
 {pickerOpen&&<div role='dialog' aria-modal='true' style={{position:'fixed',inset:0,background:'rgba(15,23,42,.48)',display:'grid',placeItems:'center',padding:20,zIndex:100}}><div style={{width:'min(900px,100%)',maxHeight:'85vh',overflow:'auto',background:'#fff',borderRadius:18,padding:22,boxShadow:'0 24px 80px rgba(15,23,42,.25)'}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'flex-start'}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1.2,color:'#0f766e'}}>RECRUITMENT → WORKFORCE</div><h2 style={{margin:'4px 0'}}>Choose a recruitment intake</h2><p style={{margin:0,color:'#627d98'}}>Select a candidate. You never type or assign the BIMED ID manually.</p></div><button onClick={()=>setPickerOpen(false)} style={{padding:'8px 10px',border:'1px solid #d9e2ec',background:'#fff',borderRadius:8}}>Close</button></div><input value={candidateSearch} onChange={e=>setCandidateSearch(e.target.value)} placeholder='Search candidate, email, role or status' style={{width:'100%',boxSizing:'border-box',padding:11,margin:'18px 0 12px',border:'1px solid #d9e2ec',borderRadius:10}}/>{candidateBusy?<div style={{padding:20,color:'#627d98'}}>Loading eligible recruitment intakes…</div>:visibleCandidates.length===0?<div style={{padding:20,border:'1px dashed #cbd5e1',borderRadius:12,color:'#627d98'}}>No eligible recruitment intakes are currently available to promote.</div>:<div style={{display:'grid',gap:10}}>{visibleCandidates.map(c=><div key={c.id} style={{border:'1px solid #e5eaf0',borderRadius:13,padding:14,display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontWeight:900}}>{c.full_name}</div><div style={{fontSize:13,color:'#627d98'}}>{c.email} · {c.role_applied||'Role pending'}</div><div style={{fontSize:12,color:'#829ab1',marginTop:3}}>{c.status}{c.living_in_ireland==='No'?' · Pre-arrival':''}</div></div><button disabled={!!promotingId} onClick={()=>void promote(c.id)} style={{padding:'10px 13px',border:0,borderRadius:9,background:'#0f766e',color:'#fff',fontWeight:800}}>{promotingId===c.id?'Creating…':'Create staff identity'}</button></div>)}</div>}</div></div>}
 </div></main>
}
