'use client';

import { useEffect, useState } from 'react';

type Row = { id: string; participants: any[]; latest: any };
type Message = { id: string; sender_staff_id: string | null; sender_admin_email: string | null; body: string; created_at: string };

export default function AdminMessagesPage() {
  const [rows, setRows] = useState<Row[]>([]); const [active, setActive] = useState(''); const [messages, setMessages] = useState<Message[]>([]); const [draft, setDraft] = useState(''); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  async function load() { const r = await fetch('/api/admin/messages', { cache: 'no-store' }); if (!r.ok) { setError('Unable to load message oversight.'); return; } const d = await r.json(); setRows(d.conversations || []); }
  async function open(id: string) { setActive(id); const r = await fetch(`/api/admin/messages/${id}`, { cache: 'no-store' }); if (!r.ok) { setError('Unable to open conversation.'); return; } const d = await r.json(); setMessages(d.messages || []); }
  useEffect(() => { void load(); }, []);
  async function reply() { if (!active || !draft.trim()) return; const r = await fetch(`/api/admin/messages/${active}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ message: draft }) }); const d = await r.json(); if (!r.ok) { setError(d.error || 'Unable to send.'); return; } setMessages((m) => [...m, d.message]); setDraft(''); void load(); }
  const visible = rows.filter((r) => !search.trim() || r.participants.some((p: any) => `${p.full_name} ${p.bimed_id} ${p.address || ''}`.toLowerCase().includes(search.toLowerCase())));
  return <main style={{ minHeight: '100vh', background: '#f4f7fb', color: '#102a43', fontFamily: 'system-ui', padding: 24 }}><div style={{ maxWidth: 1300, margin: '0 auto' }}><h1 style={{ marginTop: 0 }}>BIMED Message Centre</h1><p style={{ color: '#627d98' }}>Administrative oversight of staff conversations. Staff do not receive a searchable directory.</p><div style={{ display: 'grid', gridTemplateColumns: '390px minmax(0,1fr)', gap: 16, background: '#fff', border: '1px solid #e5eaf0', borderRadius: 16, overflow: 'hidden', minHeight: 700 }}><aside style={{ padding: 14, borderRight: '1px solid #edf2f7' }}><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search staff, BIMED ID or handle" style={{ width: '100%', boxSizing: 'border-box', padding: 11, border: '1px solid #cbd5e1', borderRadius: 10, marginBottom: 12 }} />{visible.map((r) => <button key={r.id} onClick={() => void open(r.id)} style={{ width: '100%', textAlign: 'left', border: 0, background: active === r.id ? '#e6fffb' : '#fff', borderRadius: 10, padding: 12, marginBottom: 7 }}><strong>{r.participants.map((p: any) => p.preferred_name || p.full_name).join(' ↔ ')}</strong><div style={{ fontSize: 12, color: '#627d98' }}>{r.participants.map((p: any) => p.address).filter(Boolean).join(' · ')}</div><div style={{ fontSize: 12, color: '#829ab1', marginTop: 4 }}>{r.latest?.body || ''}</div></button>)}</aside><section style={{ display: 'flex', flexDirection: 'column' }}>{!active ? <div style={{ margin: 'auto', color: '#627d98' }}>Select a conversation.</div> : <><div style={{ padding: 16, borderBottom: '1px solid #edf2f7', fontWeight: 900 }}>Conversation oversight</div><div style={{ flex: 1, overflowY: 'auto', padding: 18, display: 'grid', alignContent: 'start', gap: 10 }}>{messages.map((m) => <div key={m.id} style={{ maxWidth: '80%', justifySelf: m.sender_admin_email ? 'end' : 'start', background: m.sender_admin_email ? '#0f766e' : '#f4f7fb', color: m.sender_admin_email ? '#fff' : '#243b53', borderRadius: 14, padding: '10px 13px' }}><div style={{ fontSize: 11, fontWeight: 800, opacity: .75, marginBottom: 3 }}>{m.sender_admin_email ? 'BIMED Admin' : 'Staff'}</div><div style={{ whiteSpace: 'pre-wrap' }}>{m.body}</div><div style={{ fontSize: 10, opacity: .7, marginTop: 5 }}>{new Date(m.created_at).toLocaleString('en-IE')}</div></div>)}</div><div style={{ padding: 14, borderTop: '1px solid #edf2f7', display: 'flex', gap: 8 }}><textarea value={draft} onChange={(e) => setDraft(e.target.value)} rows={2} placeholder="Reply as BIMED Admin…" style={{ flex: 1, padding: 10, border: '1px solid #cbd5e1', borderRadius: 10 }} /><button onClick={() => void reply()} style={{ padding: '10px 16px', border: 0, borderRadius: 10, background: '#0f766e', color: '#fff', fontWeight: 900 }}>Send</button></div></>}</section></div>{error && <p style={{ color: '#b42318' }}>{error}</p>}</div></main>;
}
