'use client';

import { useRouter } from 'next/navigation';

const faq = [
  ['Is the €4,000 an employment-permit fee?', 'No. BIMED treats it as a separate accommodation contribution for the initial three-month accommodation arrangement. BIMED is responsible for the employer-side employment-permit process and applicable employer costs.'],
  ['Why is the exact apartment address not provided yet?', 'BIMED is coordinating accommodation for a large intake across several locations. For overseas recruits, the accommodation is allocated with reference to the employee’s primary place of assignment. Once the recruitment, accommodation and payment arrangements are completed, final relocation documentation will contain the primary assignment, accommodation address, property details and relevant building-management contact information.'],
  ['Who is the tenant during the first three months?', 'BIMED remains the corporate tenant under the relevant accommodation arrangement for the initial three-month period. The building management company therefore deals with BIMED as the tenant rather than entering into a separate individual three-month tenancy with each recruit.'],
  ['Can I negotiate different rental terms or request a different apartment?', 'Not independently during the corporate tenancy period. BIMED manages the accommodation arrangement. A recruit should not independently negotiate different rental terms, request a refund from the building management company or require a change of apartment. Genuine property issues can be reported through the appropriate accommodation or building-management channel, and BIMED will assist where necessary.'],
  ['Where do I send the €4,000?', 'Only to the corporate payment details shown on the official accommodation invoice issued through the BIMED Staff Portal process. Never pay a BIMED employee, recruiter, manager or representative personally.'],
  ['Who should make the payment?', 'The payment should normally be made personally from an account held in the recruit’s own name. A payment from another individual’s account or by a third party may not be accepted because BIMED must be able to reconcile the transaction with the accommodation documentation. Where a business or company account is proposed, BIMED may require evidence that the recruit is authorised to operate the account and make the payment on the company’s behalf.'],
  ['When does the three-month accommodation period begin?', 'The three-month accommodation arrangement begins on the date you move into the allocated accommodation or 11 January 2027, whichever occurs first, in accordance with the applicable accommodation terms.'],
  ['Is the €4,000 refundable?', 'Subject to the agreed accommodation conditions and successful completion of the three-month probationary period, the full €4,000 is refunded in four weekly instalments. The applicable terms also address qualifying permit or visa refusal refunds and other circumstances that may affect refund eligibility.'],
  ['Does paying the €4,000 guarantee my permit or visa?', 'No. Payment does not guarantee an employment permit, visa, right to work, entry to Ireland or continued employment. The relevant authorities make those decisions.'],
  ['How much money do I need to show for my visa?', 'Irish employment-visa guidance requires six months of bank statements and evidence of sufficient funds for the applicant’s circumstances. The guidance does not publish one universal balance that applies to every employment-visa applicant.'],
];

export default function RelocationInformationPage() {
  const router = useRouter();
  return <main style={{ minHeight: '100vh', background: '#f4f7fb', color: '#102a43', fontFamily: 'system-ui', padding: 'clamp(16px,4vw,30px)' }}>
    <div style={{ width: 'min(1050px,100%)', margin: '0 auto' }}>
      <button onClick={() => router.push('/staff')} style={secondary}>← Staff Portal</button>
      <header style={{ marginTop: 18 }}><div style={eyebrow}>OVERSEAS RELOCATION · OFFICIAL INFORMATION</div><h1 style={{ fontSize: 'clamp(30px,6vw,48px)', lineHeight: 1.05, margin: '5px 0' }}>Accommodation & relocation guide</h1><p style={{ maxWidth: 820, color: '#627d98', fontSize: 17, lineHeight: 1.65 }}>This page explains BIMED’s current relocation arrangement, including the €4,000 accommodation contribution, corporate-tenancy structure, allocation process, final documentation, refund arrangement and payment-verification rules.</p></header>
      <section style={{ ...card, background: '#163247', color: '#fff', border: 0 }}><div style={{ display: 'grid', gridTemplateColumns: '1.5fr .7fr', gap: 20, alignItems: 'center' }}><div><div style={{ fontSize: 12, letterSpacing: 1.2, fontWeight: 900, color: '#8fe4dc' }}>THE KEY POINT</div><h2 style={{ margin: '7px 0 8px', fontSize: 26 }}>The €4,000 is an accommodation contribution, not a permit or visa fee.</h2><p style={{ margin: 0, color: '#d7e7ef', lineHeight: 1.65 }}>It applies to the BIMED-arranged accommodation package for the initial three-month period.</p></div><div style={{ textAlign: 'center' }}><div style={{ fontSize: 12, color: '#b8ced9' }}>ACCOMMODATION CONTRIBUTION</div><div style={{ fontSize: 42, fontWeight: 950, marginTop: 2 }}>€4,000</div></div></div></section>
      <section style={card}><h2 style={h2}>Why BIMED is using this accommodation structure</h2><p style={copy}>BIMED is currently onboarding more than 30 recruits from Ireland, the EEA and overseas. As part of this recruitment programme, BIMED is arranging suitable accommodation for incoming staff. This is intended to support the relocation process and, where applicable, provide accommodation information relevant to visa preparation, while also helping new employees settle into living and working in Ireland without an immediate housing search on arrival.</p><p style={copy}>Because BIMED is coordinating accommodation for a significant number of recruits, it has arrangements with multiple building management companies and properties in different locations. BIMED will remain the corporate tenant for the initial three-month period under the relevant accommodation arrangements.</p></section>
      <section style={card}><h2 style={h2}>Primary assignment and accommodation allocation</h2><p style={copy}>For overseas recruits, accommodation is allocated with reference to the employee’s primary place of assignment. The property is therefore not selected independently of the employment placement. BIMED first completes the relevant recruitment, accommodation and payment arrangements before allocating the recruit to a particular care home or assisted-living facility and suitable accommodation in relation to that assignment.</p><p style={copy}>This is why the exact apartment address may not be available at the initial stage. Once the arrangements have been completed and the property has been allocated, final employment and relocation documentation will contain the place of primary assignment, which may differ from BIMED’s head-office address, together with the accommodation address, relevant property details and building-management contact information.</p></section>
      <section style={card}><h2 style={h2}>Accommodation and corporate tenancy</h2><div style={grid}>{[['BIMED is the corporate tenant','The accommodation agreement is between BIMED and the relevant building management company for the initial three-month period.'],['The building manager is a property contact','Receiving the building manager’s contact details does not make the recruit the contractual tenant during the initial corporate tenancy period.'],['No independent rent negotiation','A recruit cannot independently negotiate different rental terms, request a refund from the building management company or require a change of apartment during the corporate tenancy period.'],['Property issues can still be reported','Genuine accommodation or property issues may be reported through the appropriate accommodation or building-management channel, with BIMED assisting where necessary.']].map(([title,text]) => <div key={title} style={subcard}><strong>{title}</strong><p>{text}</p></div>)}</div></section>
      <section style={card}><h2 style={h2}>What the €4,000 covers</h2><p style={copy}>The €4,000 is the employee accommodation contribution for the initial three-month period. It is not an employment-permit fee and is not a payment being made to BIMED staff. The exact property allocated to the recruit is confirmed through the relocation process.</p></section>
      <section style={card}><h2 style={h2}>Payment verification and source of funds</h2><div style={warning}><strong>Use only official corporate payment instructions.</strong><p style={{ margin: '7px 0 0' }}>The payment and transaction evidence provided to BIMED must correspond with the official accommodation documentation. The payment should normally be made by the recruit personally from an account held in the recruit’s own name. Do not use another individual’s bank account or ask a third party to pay on your behalf.</p><p style={{ margin: '10px 0 0' }}>Where payment from a business or company account is proposed, BIMED may require evidence that the recruit is authorised to operate the account and make the payment on behalf of the company, such as company registration documentation and evidence of director or authorised-representative status. Any payment that cannot be properly verified may not be accepted as satisfying the accommodation requirement.</p></div></section>
      <section style={card}><h2 style={h2}>Commencement of the accommodation period</h2><p style={copy}>The three-month accommodation arrangement will commence on the date you move into the allocated accommodation or <strong>11 January 2027</strong>, whichever occurs first, in accordance with the applicable accommodation terms. The accommodation contribution and three-month period are therefore linked to the formal relocation arrangement rather than simply to the date on which an individual chooses to move into the property.</p></section>
      <section style={card}><h2 style={h2}>Allocation and final documentation</h2><p style={copy}>Once the required arrangements have been completed, including confirmation of the accommodation contribution, BIMED can proceed with final allocation. Your final documentation will contain:</p><div style={grid}>{[['Primary assignment','Your place of primary assignment and relevant reporting location.'],['Accommodation address','The address of the property allocated to you.'],['Accommodation details','The relevant property and occupancy information.'],['Building management','The appropriate building-management contact details and applicable accommodation terms.']].map(([title,text]) => <div key={title} style={subcard}><strong>{title}</strong><p>{text}</p></div>)}</div><p style={{ ...copy, marginBottom: 0, marginTop: 15 }}>The purpose is to coordinate employment placement and accommodation so that an incoming recruit is not expected to arrive in Ireland without suitable accommodation while also starting a new role and completing initial training and orientation.</p></section>
      <section style={card}><h2 style={h2}>Why payment is required before the relocation workflow proceeds</h2><p style={copy}>BIMED’s stated reason for the upfront contribution is to combine a controlled accommodation plan with a clear financial commitment from an overseas recruit before the relocation process proceeds. BIMED has stated that it has previously encountered recruits arriving without sufficient resources for their initial period, including situations where salary advances were requested during probation.</p><p style={copy}>The accommodation contribution is separate from the statutory employment-permit and visa decisions of the relevant authorities.</p></section>
      <section style={card}><h2 style={h2}>Payment safety</h2><div style={warning}><strong>Never transfer the €4,000 to a personal account.</strong><p style={{ margin: '7px 0 0' }}>No BIMED employee, recruiter, manager or representative should ask you to send the accommodation contribution to a personal bank account. Use only the official corporate payment details contained in the accommodation invoice issued through the Staff Portal process.</p></div><button onClick={() => router.push('/staff/permit')} style={primary}>Open accommodation & permit workspace</button></section>
      <section style={card}><h2 style={h2}>Refund arrangement</h2><div style={grid}>{[['Successful probation','Subject to the agreed accommodation conditions, the full €4,000 refund is processed after successful completion of the three-month probationary period and paid in four weekly instalments.'],['Qualifying refusal','Where the applicable accommodation arrangement provides for a permit or visa refusal refund, official refusal evidence is required and the refund is processed under the applicable terms.'],['Accommodation compliance','The refund is subject to the agreed accommodation conditions, including any applicable outstanding property damage or other documented accommodation issues attributable to the employee.'],['Leaving BIMED early','The refund is conditional on successful completion of probation. The accommodation terms describe circumstances in which the contribution may be forfeited.']].map(([title,text]) => <div key={title} style={subcard}><strong>{title}</strong><p>{text}</p></div>)}</div></section>
      <section style={card}><h2 style={h2}>Visa financial evidence</h2><p style={copy}>Irish employment-visa applicants should expect to provide six months of bank statements and evidence of sufficient funds for their circumstances. The official guidance also asks for details of where the applicant intends to stay and says an employer letter should include accommodation details where the employer is providing accommodation.</p><p style={copy}>There is not one universal Government bank-balance figure for every employment-visa applicant. Any practical funding range quoted by BIMED or an adviser should therefore be treated as planning guidance, not as a fixed Irish immigration threshold and not as a guarantee of visa approval.</p></section>
      <section style={card}><h2 style={h2}>Frequently asked questions</h2><div>{faq.map(([q,a]) => <details key={q} style={{ borderTop: '1px solid #e5eaf0', padding: '14px 0' }}><summary style={{ cursor: 'pointer', fontWeight: 850, color: '#243b53' }}>{q}</summary><p style={{ ...copy, marginBottom: 0, marginTop: 9 }}>{a}</p></details>)}</div></section>
      <section style={{ ...card, marginBottom: 30, background: '#ecfdf5', borderColor: '#b7ead0' }}><h2 style={h2}>Ready to request your invoice?</h2><p style={copy}>The Staff Portal accommodation workspace is where you acknowledge the arrangement and request your individual €4,000 invoice. The billing team then prepares and issues the official invoice through the BIMED process.</p><button onClick={() => router.push('/staff/permit')} style={primary}>Go to invoice request</button></section>
    </div>
  </main>;
}
const card: React.CSSProperties = { background: '#fff', border: '1px solid #e5eaf0', borderRadius: 16, padding: 'clamp(17px,3vw,23px)', marginTop: 18, boxShadow: '0 8px 28px rgba(15,23,42,.04)' };
const h2: React.CSSProperties = { marginTop: 0, color: '#163247' }; const copy: React.CSSProperties = { color: '#486581', lineHeight: 1.72 }; const grid: React.CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 12 }; const subcard: React.CSSProperties = { padding: 14, borderRadius: 12, background: '#f8fafc', border: '1px solid #e5eaf0' }; const primary: React.CSSProperties = { marginTop: 14, padding: '12px 16px', border: 0, borderRadius: 10, background: '#0f766e', color: '#fff', fontWeight: 900 }; const secondary: React.CSSProperties = { padding: '9px 12px', border: '1px solid #d9e2ec', borderRadius: 9, background: '#fff', color: '#334e68', fontWeight: 800 }; const warning: React.CSSProperties = { padding: 16, borderRadius: 12, background: '#fff7ed', border: '1px solid #fed7aa', color: '#7c2d12', lineHeight: 1.65 }; const eyebrow: React.CSSProperties = { fontSize: 12, fontWeight: 900, letterSpacing: 1.2, color: '#0f766e' };
