'use client';

import { useRouter } from 'next/navigation';

const faq = [
  ['Is the €4,000 an employment-permit fee?', 'No. BIMED treats it as a separate accommodation contribution for the initial three-month probationary accommodation arrangement. BIMED is responsible for the employer-side employment-permit process and applicable employer costs.'],
  ['What does the €4,000 cover?', 'It is the employee contribution toward BIMED-arranged, subsidised accommodation for the initial three-month probationary period. BIMED describes the arrangement as furnished Dublin accommodation, with the exact property confirmed as the relocation process progresses.'],
  ['Can I pay it in instalments or have it deducted from salary?', 'No. The current BIMED relocation terms require the contribution to be paid through the official accommodation process before BIMED proceeds with the employment-permit submission. BIMED does not use salary deduction for this contribution.'],
  ['Where do I send the money?', 'Only to the payment details shown on the official accommodation invoice issued through the BIMED Staff Portal process. Never pay a BIMED employee, recruiter, manager or representative personally.'],
  ['Is it refundable?', 'The current accommodation terms provide for the €4,000 refund after successful completion of the three-month probationary period, paid in four weekly instalments. Any qualifying permit or visa refusal refund is handled according to the applicable accommodation terms and requires official evidence.'],
  ['What if I leave the BIMED apartment after the first month?', 'The relocation arrangement allows you to arrange alternative accommodation after the initial training and shadowing period, subject to the accommodation terms. You must provide BIMED with valid proof of your new address. The three-month probationary commitment remains unchanged.'],
  ['What if I leave BIMED before three months?', 'The refund is conditional on successful completion of the three-month probationary period. The accommodation terms set out circumstances in which the contribution may be forfeited, including early resignation, abandonment, unauthorised additional employment during probation or other material breaches of the agreed arrangement.'],
  ['Does paying the €4,000 guarantee my permit or visa?', 'No. Payment does not guarantee an employment permit, visa, right to work, entry to Ireland or continued employment. The relevant authorities make those decisions.'],
  ['How much money do I need to show for my visa?', 'Irish immigration guidance requires employment-visa applicants to provide six months of bank statements and evidence of sufficient funds. It does not publish one universal balance that applies to every employment-visa applicant. BIMED may provide practical budgeting guidance, but that guidance is not an Irish Government threshold and does not guarantee visa approval.'],
];

export default function RelocationInformationPage() {
  const router = useRouter();
  return <main style={{ minHeight: '100vh', background: '#f4f7fb', color: '#102a43', fontFamily: 'system-ui', padding: 'clamp(16px,4vw,30px)' }}>
    <div style={{ width: 'min(1050px,100%)', margin: '0 auto' }}>
      <button onClick={() => router.push('/staff')} style={secondary}>← Staff Portal</button>
      <header style={{ marginTop: 18 }}><div style={eyebrow}>OVERSEAS RELOCATION · OFFICIAL INFORMATION</div><h1 style={{ fontSize: 'clamp(30px,6vw,48px)', lineHeight: 1.05, margin: '5px 0' }}>Accommodation & relocation guide</h1><p style={{ maxWidth: 820, color: '#627d98', fontSize: 17, lineHeight: 1.65 }}>This page explains BIMED's current overseas relocation arrangement, including the €4,000 accommodation contribution, invoice process, refund arrangement and important payment-safety rules.</p></header>
      <section style={{ ...card, background: '#163247', color: '#fff', border: 0 }}><div style={{ display: 'grid', gridTemplateColumns: '1.5fr .7fr', gap: 20, alignItems: 'center' }}><div><div style={{ fontSize: 12, letterSpacing: 1.2, fontWeight: 900, color: '#8fe4dc' }}>THE KEY POINT</div><h2 style={{ margin: '7px 0 8px', fontSize: 26 }}>The €4,000 is an accommodation contribution, not a permit or visa fee.</h2><p style={{ margin: 0, color: '#d7e7ef', lineHeight: 1.65 }}>It applies to the BIMED-arranged overseas-hire accommodation package for the initial three-month probationary period.</p></div><div style={{ textAlign: 'center' }}><div style={{ fontSize: 12, color: '#b8ced9' }}>ACCOMMODATION CONTRIBUTION</div><div style={{ fontSize: 42, fontWeight: 950, marginTop: 2 }}>€4,000</div></div></div></section>
      <section style={card}><h2 style={h2}>What BIMED provides</h2><div style={grid}>{[['Employment','Employment contract and employer-side recruitment documentation.'],['Permit support','BIMED handles the employer-side employment-permit process and applicable employer costs.'],['Accommodation','Subsidised BIMED-arranged accommodation for the initial three-month period.'],['Flight assistance','Economy flight assistance for the employee and, where applicable, up to two accompanying family members.'],['Airport pickup','BIMED arranges Dublin airport pickup after immigration clearance.'],['Relocation support','Employer-side support through the permit, visa and relocation preparation stages.']].map(([title,text]) => <div key={title} style={subcard}><strong>{title}</strong><p>{text}</p></div>)}</div></section>
      <section style={card}><h2 style={h2}>What the €4,000 covers</h2><p style={copy}>BIMED has arrangements with building management companies in Dublin and reserves suitable accommodation for incoming overseas employees. BIMED describes the standard arrangement as furnished one-bedroom accommodation in the Dublin 8 area, with the exact property selected in consideration of the employee's primary place of assignment. The specific address is provided as the relocation process progresses.</p><p style={copy}>The €4,000 is the employee contribution toward that arrangement. BIMED states that it already subsidises the accommodation cost, so the contribution should not be treated as the full market cost of the accommodation.</p></section>
      <section style={card}><h2 style={h2}>Why payment is required before the permit submission</h2><p style={copy}>BIMED's stated reason for the upfront contribution is to combine a controlled accommodation plan with a realistic financial commitment from an overseas recruit before relocation. BIMED says it has previously encountered recruits arriving without sufficient resources for their initial period, including situations where salary advances were requested during probation.</p><p style={copy}>The accommodation arrangement is therefore part of BIMED's current overseas relocation structure. It is separate from the statutory employment-permit and visa decisions of the relevant authorities.</p></section>
      <section style={card}><h2 style={h2}>Payment safety</h2><div style={warning}><strong>Never transfer the €4,000 to a personal account.</strong><p style={{ margin: '7px 0 0' }}>No BIMED employee, recruiter, manager or representative should ask you to send the accommodation contribution to a personal bank account. BIMED also does not require this contribution to be sent to an ordinary BIMED operating account. Only use the official payment details contained in the accommodation invoice issued through the Staff Portal process.</p></div><button onClick={() => router.push('/staff/permit')} style={primary}>Open accommodation & permit workspace</button></section>
      <section style={card}><h2 style={h2}>Refund arrangement</h2><div style={grid}>{[['Successful probation','Full €4,000 refund after successful completion of the three-month probationary period, paid in four weekly instalments under the accommodation terms.'],['Qualifying refusal','Where the applicable accommodation arrangement provides for a permit or visa refusal refund, official refusal evidence is required and the refund is processed under the applicable terms.'],['Leaving accommodation early','Alternative accommodation may be arranged after the initial training and shadowing period, subject to the accommodation terms and proof of the new address.'],['Leaving BIMED early','The refund is conditional on successful probation. The accommodation terms describe circumstances in which the contribution may be forfeited.']].map(([title,text]) => <div key={title} style={subcard}><strong>{title}</strong><p>{text}</p></div>)}</div></section>
      <section style={card}><h2 style={h2}>Visa financial evidence</h2><p style={copy}>Irish employment-visa applicants should expect to provide six months of bank statements and evidence of sufficient funds for their circumstances. There is not one universal Government bank-balance figure for every employment-visa applicant.</p><p style={copy}>Any practical funding range quoted by BIMED or a visa adviser should therefore be treated as planning guidance, not as a fixed Irish immigration threshold and not as a guarantee of visa approval.</p></section>
      <section style={card}><h2 style={h2}>Frequently asked questions</h2><div>{faq.map(([q,a]) => <details key={q} style={{ borderTop: '1px solid #e5eaf0', padding: '14px 0' }}><summary style={{ cursor: 'pointer', fontWeight: 850, color: '#243b53' }}>{q}</summary><p style={{ ...copy, marginBottom: 0, marginTop: 9 }}>{a}</p></details>)}</div></section>
      <section style={{ ...card, marginBottom: 30, background: '#ecfdf5', borderColor: '#b7ead0' }}><h2 style={h2}>Ready to request your invoice?</h2><p style={copy}>The Staff Portal accommodation workspace is where you acknowledge the arrangement and request your individual €4,000 invoice. The billing team then prepares and issues the official invoice through the BIMED process.</p><button onClick={() => router.push('/staff/permit')} style={primary}>Go to invoice request</button></section>
    </div>
  </main>;
}
const card: React.CSSProperties = { background: '#fff', border: '1px solid #e5eaf0', borderRadius: 16, padding: 'clamp(17px,3vw,23px)', marginTop: 18, boxShadow: '0 8px 28px rgba(15,23,42,.04)' };
const h2: React.CSSProperties = { marginTop: 0, color: '#163247' }; const copy: React.CSSProperties = { color: '#486581', lineHeight: 1.72 }; const grid: React.CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 12 }; const subcard: React.CSSProperties = { padding: 14, borderRadius: 12, background: '#f8fafc', border: '1px solid #e5eaf0' }; const primary: React.CSSProperties = { marginTop: 14, padding: '12px 16px', border: 0, borderRadius: 10, background: '#0f766e', color: '#fff', fontWeight: 900 }; const secondary: React.CSSProperties = { padding: '9px 12px', border: '1px solid #d9e2ec', borderRadius: 9, background: '#fff', color: '#334e68', fontWeight: 800 }; const warning: React.CSSProperties = { padding: 16, borderRadius: 12, background: '#fff7ed', border: '1px solid #fed7aa', color: '#7c2d12', lineHeight: 1.65 }; const eyebrow: React.CSSProperties = { fontSize: 12, fontWeight: 900, letterSpacing: 1.2, color: '#0f766e' };
