'use client';

import { useSearchParams, useRouter } from 'next/navigation';
import { Suspense, useState } from 'react';

function ActivateForm() {
  const params = useSearchParams(); const router = useRouter();
  const token = params.get('token') || ''; const initialEmail = params.get('email') || '';
  const [email,setEmail]=useState(initialEmail); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setError('');if(password!==confirm){setError('Passwords do not match.');return}setBusy(true);try{const r=await fetch('/api/staff/auth/activate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Activation failed.');router.replace('/staff')}catch(x){setError(x instanceof Error?x.message:'Activation failed.')}finally{setBusy(false)}}
  return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#f4f7fb',padding:24}}><form onSubmit={submit} style={{width:'100%',maxWidth:480,background:'#fff',padding:32,borderRadius:20,boxShadow:'0 14px 44px rgba(15,23,42,.08)'}}><div style={{fontSize:13,fontWeight:800,letterSpacing:1.4,textTransform:'uppercase',color:'#0f766e'}}>BIMED Healthcare</div><h1 style={{fontSize:29,color:'#102a43',margin:'10px 0 8px'}}>Activate your staff account</h1><p style={{color:'#627d98',marginBottom:24}}>Your BIMED ID will remain with you throughout your time with BIMED Healthcare.</p><label style={{display:'block',fontWeight:700,marginBottom:6}}>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} type='email' required style={{width:'100%',padding:'12px 14px',border:'1px solid #d9e2ec',borderRadius:10,marginBottom:16}}/><label style={{display:'block',fontWeight:700,marginBottom:6}}>Create password</label><input value={password} onChange={e=>setPassword(e.target.value)} type='password' minLength={10} required style={{width:'100%',padding:'12px 14px',border:'1px solid #d9e2ec',borderRadius:10,marginBottom:16}}/><label style={{display:'block',fontWeight:700,marginBottom:6}}>Confirm password</label><input value={confirm} onChange={e=>setConfirm(e.target.value)} type='password' minLength={10} required style={{width:'100%',padding:'12px 14px',border:'1px solid #d9e2ec',borderRadius:10,marginBottom:16}}/>{error&&<div style={{background:'#fff5f5',border:'1px solid #fed7d7',color:'#c53030',padding:12,borderRadius:10,marginBottom:16}}>{error}</div>}<button disabled={busy||!token} style={{width:'100%',padding:'13px 16px',border:0,borderRadius:10,background:'#0f766e',color:'#fff',fontWeight:800}}>{busy?'Activating…':'Activate BIMED account'}</button></form></main>
}
export default function ActivatePage(){return <Suspense fallback={<main style={{padding:40}}>Loading…</main>}><ActivateForm/></Suspense>}
