import type { SupabaseClient } from '@supabase/supabase-js';
import { getOrCreateDirectConversation } from '@/lib/staff-messaging';

const DUFFEL_API_URL = 'https://api.duffel.com';
const NOTICE_HOURS = 72;
export const DUBLIN = { code: 'DUB', name: 'Dublin Airport', city: 'Dublin', country: 'Ireland' } as const;
export type FlightPassengerInput = { full_name: string; date_of_birth: string };
export type Airport = { code: string; name: string; city: string; country_code: string; country_name: string };

function ageAt(dob: string, date: string) { const b = new Date(`${dob}T00:00:00Z`); const t = new Date(`${date}T00:00:00Z`); let age = t.getUTCFullYear() - b.getUTCFullYear(); const m = t.getUTCMonth() - b.getUTCMonth(); if (m < 0 || (m === 0 && t.getUTCDate() < b.getUTCDate())) age -= 1; return age; }
function validate(passengers: FlightPassengerInput[], date: string) { if (!Array.isArray(passengers) || passengers.length < 1 || passengers.length > 3) throw new Error('BIMED can arrange a maximum of 3 passengers per travel request.'); const seen = new Set<string>(); for (const p of passengers) { const name = p.full_name?.trim(); if (!name || name.length < 3) throw new Error('Every passenger needs a full legal name.'); if (!/^\d{4}-\d{2}-\d{2}$/.test(p.date_of_birth)) throw new Error('Every passenger needs a valid date of birth.'); if (ageAt(p.date_of_birth, date) < 0) throw new Error('Passenger date of birth cannot be after the travel date.'); const key = `${name.toLowerCase()}|${p.date_of_birth}`; if (seen.has(key)) throw new Error('Duplicate passenger details were entered.'); seen.add(key); } }
function token() { const value = process.env.DUFFEL_ACCESS_TOKEN || ''; if (!value) throw new Error('Live flight search is not configured yet. BIMED needs a live DUFFEL_ACCESS_TOKEN on the production service.'); if (value.startsWith('duffel_test_')) throw new Error('BIMED is still using a Duffel test token. Replace it with the live token before creating real-price itineraries.'); return value; }

export async function createVirtualFlightItinerary(input: { client: SupabaseClient; staff: any; permit: any; origin: Airport; travelDate: string; passengers: FlightPassengerInput[] }) {
  validate(input.passengers, input.travelDate);
  const passengers = input.passengers.map((p) => ({ type: ageAt(p.date_of_birth, input.travelDate) < 2 ? 'infant_without_seat' : ageAt(p.date_of_birth, input.travelDate) < 12 ? 'child' : 'adult' }));
  const response = await fetch(`${DUFFEL_API_URL}/air/offer_requests?return_offers=true&view=itineraries`, { method: 'POST', headers: { Authorization: `Bearer ${token()}`, 'Content-Type': 'application/json', Accept: 'application/json', 'Duffel-Version': 'v2' }, body: JSON.stringify({ slices: [{ origin: input.origin.code, destination: DUBLIN.code, departure_date: input.travelDate }], passengers, cabin_class: 'economy' }) });
  const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.errors?.[0]?.message || body?.message || 'The live flight provider could not return offers.');
  const offers = Array.isArray(body?.data?.offers) ? body.data.offers : [];
  const parsed = offers.map((offer: any) => { const segments = (offer.slices?.[0]?.segments || []).map((s: any) => ({ marketing_carrier: s.marketing_carrier?.name || '', operating_carrier: s.operating_carrier?.name || '', flight_number: s.marketing_carrier_flight_number || s.flight_number || '', origin_code: s.origin?.iata_code || '', origin_name: s.origin?.name || '', destination_code: s.destination?.iata_code || '', destination_name: s.destination?.name || '', departing_at: s.departing_at, arriving_at: s.arriving_at })); return { id: String(offer.id), total_amount: Number(offer.total_amount || 0), currency: offer.total_currency || 'EUR', expires_at: offer.expires_at || null, airline: segments[0]?.operating_carrier || segments[0]?.marketing_carrier || 'Airline', segments }; }).filter((offer: any) => offer.id && offer.total_amount > 0 && offer.segments.length).sort((a: any, b: any) => a.total_amount - b.total_amount);
  if (!parsed.length) throw new Error('No live economy flights were returned for this route and date. Choose another date.');
  const cheapest = parsed[0]; const now = new Date().toISOString();
  const generated = { route: `${input.origin.code} → DUB`, origin_code: input.origin.code, origin_name: input.origin.name, destination_code: DUBLIN.code, destination_name: DUBLIN.name, home_country: input.origin.country_name, travel_date: input.travelDate, passenger_count: input.passengers.length, passengers: input.passengers, cabin_class: 'economy', airline: cheapest.airline, total_amount: cheapest.total_amount, currency: cheapest.currency, offer_id: cheapest.id, offer_expires_at: cheapest.expires_at, segments: cheapest.segments, alternatives: parsed.slice(1, 4).map((o: any) => ({ offer_id: o.id, airline: o.airline, total_amount: o.total_amount, currency: o.currency, expires_at: o.expires_at })), change_notice_hours: NOTICE_HOURS, airport_pickup_required: true, status: 'virtual', generated_at: now, provider: 'Duffel live flight offers' };
  const { data: saved, error } = await input.client.from('recruitment_flight_itineraries').upsert({ permit_case_id: input.permit.id, route: generated.route, departure_airport_code: generated.origin_code, departure_airport_name: generated.origin_name, destination_airport_code: generated.destination_code, destination_airport_name: generated.destination_name, travel_date: generated.travel_date, passenger_count: generated.passenger_count, cabin_class: 'economy', passengers: generated.passengers, status: 'virtual', airline_note: 'BIMED will book the cheapest suitable economy flight available at the time of actual booking.', change_notice_hours: NOTICE_HOURS, baggage_note: 'Any baggage above the airline economy allowance is the staff member’s responsibility and cost.', airport_pickup_included: true, updated_at: now }, { onConflict: 'permit_case_id' }).select('*').single();
  if (error || !saved) throw error || new Error('Unable to save the virtual itinerary.');
  await input.client.from('recruitment_staff_permit_cases').update({ flight_request_status: 'submitted', flight_request_submitted_at: now, flight_home_country: generated.home_country, flight_departure_airport_code: generated.origin_code, flight_departure_airport_name: generated.origin_name, flight_destination_airport_code: generated.destination_code, flight_destination_airport_name: generated.destination_name, flight_passenger_count: generated.passenger_count, flight_passengers: generated.passengers, flight_travel_date: generated.travel_date, flight_cabin_class: 'economy', flight_virtual_itinerary: generated, flight_itinerary_generated_at: now, flight_staff_notice_hours: NOTICE_HOURS, flight_airport_pickup_required: true, flight_updated_at: now, updated_at: now }).eq('id', input.permit.id);
  const message = `VIRTUAL FLIGHT ITINERARY REQUEST\n\nStaff: ${input.staff.full_name}\nBIMED ID: ${input.staff.bimed_id}\nHome-country departure: ${generated.origin_code} · ${generated.origin_name}\nDestination: DUB · Dublin Airport, Ireland\nTravel date: ${generated.travel_date}\nPassengers: ${generated.passenger_count}\nCabin: Economy\n\nLOWEST LIVE OFFER FOUND\nAirline: ${generated.airline}\nQuoted fare: ${generated.total_amount.toFixed(2)} ${generated.currency}\nOffer expires: ${generated.offer_expires_at || 'Provider did not return an expiry'}\n\n${generated.segments.map((s: any, i: number) => `${i + 1}. ${s.origin_code} ${s.origin_name} → ${s.destination_code} ${s.destination_name}\n   ${s.operating_carrier || s.marketing_carrier} ${s.flight_number} · depart ${s.departing_at} · arrive ${s.arriving_at}`).join('\n')}\n\nBIMED TRAVEL RULES\n• Virtual itinerary only. Staff do not book or pay for the flight. BIMED books after visa clearance.\n• BIMED may alter departure location or routing and will give up to 72 hours' notice where a change is required.\n• BIMED reserves the right to book the cheapest suitable economy fare available at actual booking time.\n• Maximum 3 passengers.\n• Baggage above the airline economy allowance is the staff member’s cost.\n• Airport pickup to BIMED accommodation is included in the travel plan.`;
  const { data: overseas } = await input.client.from('recruitment_staff').select('id').eq('email', 'overseas@bimedhealthcare.com').maybeSingle();
  if (overseas?.id) { const conversation = await getOrCreateDirectConversation(input.client, input.staff.id, overseas.id); const { data: msg } = await input.client.from('recruitment_staff_messages').insert({ conversation_id: conversation.id, sender_staff_id: input.staff.id, body: message }).select('id,created_at').single(); if (msg) await input.client.from('recruitment_staff_conversations').update({ last_message_at: msg.created_at, updated_at: msg.created_at }).eq('id', conversation.id); }
  return { itinerary: saved, generated, message };
}
