export type StaffHelpArticle = {
  id: string;
  title: string;
  category: string;
  keywords: string[];
  answer: string;
  links?: { label: string; href: string }[];
};

export const STAFF_HELP_CATEGORIES = [
  'Getting started',
  'Staff Portal',
  'Recruitment & onboarding',
  'Accommodation & €4,000',
  'Permit & visa',
  'Travel to Ireland',
  'Work & shifts',
  'Pay & profile',
  'Messages & notifications',
  'Security & access',
] as const;

export const STAFF_HELP_ARTICLES: StaffHelpArticle[] = [
  { id:'welcome', title:'What is the BIMED Staff Portal?', category:'Getting started', keywords:['portal','staff portal','what is this','start','begin'], answer:'The BIMED Staff Portal is your employee workspace. Depending on your role and recruitment status, it can provide your BIMED ID, profile, messages, rota, attendance, notifications, payslips and recruitment-linked workspaces such as onboarding, accommodation and relocation, employment-permit preparation and travel planning.', links:[{label:'Open Dashboard',href:'/staff'}] },
  { id:'bimed-id', title:'What is my BIMED ID?', category:'Staff Portal', keywords:['bimed id','employee id','staff id','identifier','number'], answer:'Your BIMED ID is assigned automatically by BIMED. It is shown on your Staff Portal dashboard and profile and is intended to remain your employment identity throughout your BIMED employment. You do not choose or edit it.' },
  { id:'login', title:'How do I access my Staff Portal?', category:'Getting started', keywords:['login','log in','sign in','password','access','account'], answer:'Use the BIMED Staff Portal login page with the credentials or activation route provided to you. If you are newly activated, follow the activation instructions sent by BIMED. Never send your password to a recruiter, colleague or manager. Sign out after using a shared computer.', links:[{label:'Staff login',href:'/staff/login'}] },
  { id:'profile', title:'What can I change in My Profile?', category:'Pay & profile', keywords:['profile','phone','address','pps','photograph','photo','personal details'], answer:'You can maintain your phone number, address and PPS number in My Profile. You can also upload your staff photograph. Your BIMED ID is read-only. Before you have a PPS number in Ireland, you can leave it blank and add it later when it is available.', links:[{label:'Open My Profile',href:'/staff'}] },
  { id:'photo', title:'How do I add or change my staff photo?', category:'Pay & profile', keywords:['photo','photograph','picture','profile picture','headshot'], answer:'Open My Profile from the Staff Portal dashboard and upload your photograph through the profile photo control. If an upload fails, check the error shown by the portal and contact BIMED if the problem persists.' },
  { id:'onboarding', title:'What does onboarding show?', category:'Recruitment & onboarding', keywords:['onboarding','verification','checks','documents','identity','qualification'], answer:'For recruitment-linked staff, the onboarding workspace shows the controlled verification record that BIMED manages after portal access. Identity and qualification evidence were reviewed before staff access was issued. The post-access checks can include references, right-to-work verification and international work-permission verification. A check marked Pending means BIMED still has a controlled workflow step to complete. The staff view does not let you change an outcome.', links:[{label:'Open onboarding',href:'/staff/onboarding'}] },
  { id:'onboarding-correction', title:'How do I correct an onboarding or verification issue?', category:'Recruitment & onboarding', keywords:['correction','verification issue','wrong information','check','pending','error'], answer:'The employee onboarding view is intentionally read-only for verification outcomes. Contact the BIMED recruitment, immigration or HR team and ask them to review the relevant check. This preserves the controlled audit trail.', links:[{label:'Send a message to BIMED',href:'/staff/messages'}] },
  { id:'accommodation-amount', title:'What is the €4,000 accommodation contribution?', category:'Accommodation & €4,000', keywords:['4000','€4000','accommodation','payment','contribution','fee','rent'], answer:'For the overseas-hire accommodation workflow, BIMED documents a €4,000 contribution for the initial three-month accommodation arrangement. It is a separate accommodation contribution, not an employment-permit fee and not a payment to a BIMED employee personally.', links:[{label:'Open relocation guide',href:'/staff/relocation'},{label:'Open permit & accommodation',href:'/staff/permit'}] },
  { id:'accommodation-is-not-visa-fee', title:'Is the €4,000 a visa or employment-permit fee?', category:'Accommodation & €4,000', keywords:['permit fee','visa fee','immigration fee','4000 fee','employment permit'], answer:'No. BIMED describes the €4,000 as an accommodation contribution for the initial three-month accommodation arrangement. It does not guarantee an employment permit, visa, right to work, entry to Ireland or continued employment. Decisions on immigration permission are made by the relevant authorities.' },
  { id:'accommodation-payment-safety', title:'Where should I pay the €4,000?', category:'Accommodation & €4,000', keywords:['where pay','bank account','account details','payment details','personal account','scam','fraud'], answer:'Use only the official corporate payment details shown on the accommodation invoice issued through the BIMED Staff Portal process. Never transfer the €4,000 to a personal account belonging to a recruiter, manager, employee or representative. If someone asks you to do that, stop and contact BIMED through an official channel.', links:[{label:'Open accommodation workspace',href:'/staff/permit'}] },
  { id:'accommodation-source-of-funds', title:'Who should make the €4,000 payment?', category:'Accommodation & €4,000', keywords:['third party','source of funds','own account','company account','business account','payment source'], answer:'The payment should normally be made from an account held in the recruit’s own name. A third-party payment may not be accepted because BIMED needs to reconcile the payment with the accommodation documentation. If a business or company account is proposed, BIMED may require evidence that the recruit is authorised to operate that account and make the payment on the company’s behalf.' },
  { id:'accommodation-address', title:'Why do I not have my apartment address yet?', category:'Accommodation & €4,000', keywords:['apartment','address','house','property','where will i live','accommodation address'], answer:'BIMED is coordinating accommodation across multiple properties and locations. For overseas recruits, accommodation is allocated with reference to the primary place of assignment. The exact property may therefore be confirmed later, after the relevant recruitment, accommodation and payment arrangements. Final relocation documentation is intended to contain the primary assignment, accommodation address, property details and building-management contact.', links:[{label:'Read relocation guide',href:'/staff/relocation'}] },
  { id:'corporate-tenancy', title:'Who is the tenant during the initial accommodation period?', category:'Accommodation & €4,000', keywords:['tenant','corporate tenant','landlord','building manager','tenancy','rental'], answer:'BIMED remains the corporate tenant under the relevant accommodation arrangement during the initial three-month period. The building-management company therefore deals with BIMED as the tenant rather than creating an individual three-month tenancy for each recruit during that corporate period.' },
  { id:'accommodation-change', title:'Can I negotiate a different apartment or different rental terms?', category:'Accommodation & €4,000', keywords:['change apartment','different apartment','negotiate rent','rental terms','refund building manager'], answer:'Not independently during the initial corporate-tenancy period. BIMED manages the accommodation arrangement. Genuine property issues should be reported through the appropriate accommodation or building-management channel so BIMED can assist.' },
  { id:'accommodation-start', title:'When does the three-month accommodation period begin?', category:'Accommodation & €4,000', keywords:['three months','3 months','start accommodation','move in','11 january 2027','probation'], answer:'Under the current accommodation terms in the portal, the three-month accommodation arrangement starts on the date you move into the allocated accommodation or 11 January 2027, whichever occurs first. The arrangement is linked to the formal relocation terms rather than simply to an individual preference about when to move.' },
  { id:'accommodation-refund', title:'When is the €4,000 refunded?', category:'Accommodation & €4,000', keywords:['refund','refunds','money back','successful probation','four weekly instalments','weekly instalments','refusal'], answer:'The current accommodation terms state that, subject to the agreed conditions, successful completion of the three-month probationary period triggers a full €4,000 refund paid in four weekly instalments. The applicable terms also address qualifying permit or visa refusal refunds and other circumstances that can affect refund eligibility. The portal terms and issued invoice govern the specific case.', links:[{label:'Read relocation terms',href:'/staff/relocation'}] },
  { id:'accommodation-guarantee', title:'Does paying €4,000 guarantee my permit or visa?', category:'Accommodation & €4,000', keywords:['guarantee','visa approval','permit approval','entry','work right','right to work'], answer:'No. Payment does not guarantee an employment permit, visa, right to work, entry to Ireland or continued employment. Those decisions are made by the relevant authorities and the employment relationship remains subject to its stated conditions.' },
  { id:'invoice', title:'How do I request or open my accommodation invoice?', category:'Accommodation & €4,000', keywords:['invoice','request invoice','issued invoice','billing','receipt','payment reference'], answer:'In the employment-permit and accommodation workspace, acknowledge the accommodation terms first. BIMED then moves the request through its billing workflow and issues the professional accommodation invoice. Once an invoice is issued, it can be opened from the portal. Keep the invoice and payment evidence for your records.', links:[{label:'Open accommodation workspace',href:'/staff/permit'}] },
  { id:'permit-journey', title:'How does the employment-permit workflow work?', category:'Permit & visa', keywords:['employment permit','permit','sponsorship','permit journey','request sponsorship','immigration'], answer:'The portal shows your current permit status, permit type, permit application ID where available and visa status. In the current overseas-hire workflow, the accommodation arrangement is acknowledged first and the accommodation invoice must be issued before the portal unlocks the request for BIMED employment-permit assistance. BIMED then handles the employer-side permit/sponsorship workflow and uses your profile and supporting evidence.', links:[{label:'Open permit workspace',href:'/staff/permit'}] },
  { id:'work-authorisation', title:'Can I start shifts while my permit is pending?', category:'Permit & visa', keywords:['start work','work','shift','shift access','authorised','authorised to work','permit pending'], answer:'Not unless BIMED has confirmed the required permission to work in Ireland. The permit workspace explicitly keeps work unauthorised and shift eligibility blocked until the required permission is confirmed. Do not accept or work a shift when the portal says work is not authorised.' },
  { id:'visa-funds', title:'How much money must I show for my Irish employment visa?', category:'Permit & visa', keywords:['bank statements','bank balance','visa funds','six months','financial evidence','money for visa'], answer:'The current BIMED relocation guidance says employment-visa applicants should expect to provide six months of bank statements and evidence of sufficient funds for their circumstances. It does not state one universal bank-balance figure that applies to every employment-visa applicant. Treat any planning estimate from an adviser as guidance, not as a universal immigration threshold or guarantee of visa approval.', links:[{label:'Read relocation guide',href:'/staff/relocation'}] },
  { id:'travel', title:'Who books and pays for my flight to Ireland?', category:'Travel to Ireland', keywords:['flight','air ticket','ticket','travel','dublin','flight booking','airfare'], answer:'BIMED’s current pre-arrival workflow says you do not buy the flight yourself. You submit the virtual flight-planning details in the portal, then BIMED selects, pays for and books the actual economy flight after immigration clearance. BIMED also arranges and pays for the Dublin airport pickup to the assigned accommodation.', links:[{label:'Open travel planning',href:'/staff/travel'}] },
  { id:'travel-origin', title:'How is my departure airport chosen?', category:'Travel to Ireland', keywords:['departure airport','origin airport','home country','airport','country rule'], answer:'The travel workspace uses the home-country value on your recruitment record, with nationality used as a fallback where configured. BIMED may configure one departure airport for a home country, so you may not be able to select another airport yourself. Operational changes to the departure airport, routing or flight location may occur with up to 72 hours’ notice where practicable.' },
  { id:'travel-passengers', title:'How many passengers can I include in the travel request?', category:'Travel to Ireland', keywords:['passengers','family','spouse','children','travel party','three passengers'], answer:'The current Staff Portal travel-planning form supports up to three passengers. Enter each traveller’s full legal name and date of birth exactly as they should appear in the eventual booking. The flight request is a planning request, not a ticket.' },
  { id:'travel-baggage', title:'Who pays for extra baggage?', category:'Travel to Ireland', keywords:['baggage','luggage','extra luggage','bags','baggage allowance'], answer:'The current travel workflow specifies economy travel. Any baggage above the airline’s included economy allowance remains the staff member’s responsibility and cost unless BIMED separately confirms otherwise.' },
  { id:'airport-pickup', title:'Will someone pick me up at Dublin Airport?', category:'Travel to Ireland', keywords:['airport pickup','airport transfer','driver','dublin airport','pickup'], answer:'Yes, the current travel workflow says BIMED arranges and pays for the Dublin airport pickup to the assigned BIMED accommodation after immigration clearance. Confirmed driver, supplier and meeting-point details can appear in the travel workspace when assigned.' },
  { id:'rota', title:'Where do I see my shifts?', category:'Work & shifts', keywords:['rota','shift','shifts','schedule','work schedule','available work'], answer:'Use My Rota in the Staff Portal to see assigned shifts and available-work requests. The dashboard also shows upcoming shifts and recent shift requests. If you do not see a shift, do not assume you are booked for it. Wait for the portal or BIMED confirmation.', links:[{label:'Open My Rota',href:'/staff/rota'}] },
  { id:'attendance', title:'Where do I manage attendance?', category:'Work & shifts', keywords:['attendance','clock in','clock out','hours','timesheet','presence'], answer:'Use the Attendance area of the Staff Portal for your attendance information. Follow the instructions shown there for your role and report discrepancies through BIMED’s approved communication channel rather than altering records yourself.', links:[{label:'Open Attendance',href:'/staff/attendance'}] },
  { id:'payslips', title:'Where can I see my payslips?', category:'Pay & profile', keywords:['payslip','payslips','pay','salary','net pay','gross pay','payroll'], answer:'Open the Payslips area on your Staff Portal dashboard. Issued payslips show the pay period, gross pay, deductions and net pay. If no payslips have been issued yet, the portal will say so.', links:[{label:'Open Staff Portal',href:'/staff'}] },
  { id:'messages', title:'How do I contact BIMED through the portal?', category:'Messages & notifications', keywords:['message','messages','contact hr','contact admin','recruiter','ask bimed','communication'], answer:'Use Messages in the Staff Portal to contact BIMED Admin or HR and read replies. For immigration, onboarding or accommodation issues, include enough detail for BIMED to locate your record, but never send passwords or unnecessary sensitive financial information in a message.', links:[{label:'Open Messages',href:'/staff/messages'}] },
  { id:'notifications', title:'What are Staff Portal notifications?', category:'Messages & notifications', keywords:['notification','notifications','alert','unread','updates'], answer:'Notifications are portal updates connected to your staff account. Your dashboard shows an unread count and you can open the notifications workspace. You can mark notifications as read from the portal.', links:[{label:'Open Notifications',href:'/staff/notifications'}] },
  { id:'restricted', title:'Why is my portal access restricted?', category:'Security & access', keywords:['restricted','suspended','locked','access denied','portal restriction','nonpayment','payment not made'], answer:'For recruitment-linked overseas hires, BIMED can temporarily restrict staff-portal access where the controlled accommodation non-payment workflow has been triggered. The employment record and historical profile are retained, and the portal can be reactivated by BIMED after the underlying issue is resolved. The restriction does not mean the underlying staff record was deleted.' },
  { id:'security', title:'How do I keep my account safe?', category:'Security & access', keywords:['security','password','safe','account security','phishing','fraud','scam'], answer:'Keep your password private, sign out on shared devices, use only official BIMED portal links, and verify payment instructions against the official accommodation invoice. BIMED staff should not ask you to send the €4,000 to a personal bank account. Report suspicious payment requests or login activity through an official BIMED channel.' },
  { id:'general-support', title:'Who should I contact when the portal cannot answer my question?', category:'Getting started', keywords:['help','support','human','agent','hr','admin','recruitment','immigration','problem'], answer:'Use Messages to contact BIMED Admin or HR. For recruitment, permit or visa matters, the relevant BIMED recruitment or immigration team controls the next workflow step. The help assistant explains the portal but does not approve permits, alter verification outcomes, promise visa decisions or change payroll records.', links:[{label:'Open Messages',href:'/staff/messages'}] },
];

export const STAFF_HELP_QUICK_QUESTIONS = [
  'What do I need to do first?',
  'What is the €4,000 for?',
  'Where is my accommodation address?',
  'When can I start work?',
  'Who pays for my flight?',
  'How do I request my permit journey?',
  'Where do I see my shifts?',
  'Where are my payslips?',
];

export const STAFF_HELP_DISCLAIMER = 'This helper explains the current BIMED Staff Portal workflows and published recruitment guidance. It does not replace BIMED HR, recruitment or immigration staff, and it cannot guarantee permit, visa, right-to-work, employment or payroll outcomes.';
