'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';

type Staff = Record<string, any>;
type Shift = Record<string, any>;
type Payslip = Record<string, any>;
type Notice = Record<string, any>;

const card: React.CSSProperties={background:'#fff',border:'1px solid #e5eaf0',borderRadius:18,padding:20,boxShadow:'0 8px 28px rgba(15,23,42,.04)'};

export default function StaffDashboard(){
 const router=useRouter(); const [staff,setStaff]=useState<Staff|null>(null); const [shifts,setShifts]=useState<Shift[]>([]); const [requests,setRequests]=useState<any[]>([]); const [payslips,setPayslips]=useState<Payslip[]>([]); const [notifications,setNotifications]=useState<Notice[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [tab,setTab]=useState<'overview'|'rota'|'pay'|'profile'>('overview');
 const [pps,setPps]=useState(''); const [address,setAddress]=useState(''); const [phone,setPhone]=useState(''); const [photoBusy,setPhotoBusy]=useState(false);
 async function load(){setError('');const [meR,rotaR,payR,noticeR]=await Promise.all([fetch('/api/staff/me'),fetch('/api/staff/rota'),fetch('/api/staff/payslips'),fetch('/api/staff/notifications')]);if(meR.status===401){router.replace('/staff/login');return;}const [me,rota,pay,notice]=await Promise.all([meR.json(),rotaR.json(),payR.json(),noticeR.json()]);if(!meR.ok){setError(me.error||'Unable to load staff profile.');return}setStaff(me.staff);setPps(me.staff.pps_number||'');setAddress(me.staff.address_line_1||'');setPhone(me.staff.phone||'');setShifts(rota.shifts||[]);setRequests(rota.requests||[]);setPayslips(pay.payslips||[]);setNotifications(notice.notifications||[])}
 useEffect(()=>{load()},[]);
 const unread=useMemo(()=>notifications.filter(n=>!n.read_at).length,[notifications]);
 async function saveProfile(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/staff/me',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({pps_number:pps,address_line_1:address,phone})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save.');setStaff(d.staff);alert('Profile updated.')}catch(e){setError(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
 async function uploadPhoto(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setPhotoBusy(true);try{const form=new FormData();form.append('photo',file);const r=await fetch('/api/staff/me',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to upload photo.');setStaff(d.staff)}catch(e){setError(e instanceof Error?e.message:'Unable to upload photo.')}finally{setPhotoBusy(false);e.target.value=''}}
 async function logout(){await fetch('/api/staff/auth/logout',{method:'POST'});router.replace('/staff/login')}
 if(!staff)return <main style={{padding:40,fontFamily:'system-ui'}}>{error?<div>{error}</div>:'Loading BIMED Staff Portal…'}</main>;
 return <main style={{minHeight:'100vh',background:'#f4f7fb',fontFamily:'system-ui',color:'#102a43'}}>
   <header style={{background:'#fff',borderBottom:'1px solid #e5eaf0',padding:'16px 5vw',display:'flex',justifyContent:'space-between',alignItems:'center',gap:20}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1.4,color:'#0f766e',textTransform:'uppercase'}}>BIMED Healthcare</div><div style={{fontSize:22,fontWeight:800}}>Staff Portal</div></div><div style={{display:'flex',alignItems:'center',gap:12}}><div style={{textAlign:'right'}}><div style={{fontWeight:800}}>{staff.preferred_name||staff.full_name}</div><div style={{fontSize:12,color:'#627d98'}}>{staff.bimed_id}</div></div><button onClick={logout} style={{padding:'9px 12px',border:'1px solid #d9e2ec',background:'#fff',borderRadius:9}}>Sign out</button></div></header>
   <div style={{maxWidth:1200,margin:'0 auto',padding:'28px 20px'}}>
    <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:20}}>{[['overview','Overview'],['rota','My Rota'],['pay','Payslips'],['profile','My Profile']].map(([id,label])=><button key={id} onClick={()=>setTab(id as any)} style={{padding:'10px 15px',borderRadius:10,border:'1px solid #d9e2ec',background:tab===id?'#0f766e':'#fff',color:tab===id?'#fff':'#334e68',fontWeight:800}}>{label}</button>)}</div>
    {error&&<div style={{...card,borderColor:'#fed7d7',color:'#9b2c2c',marginBottom:18}}>{error}</div>}
    {tab==='overview'&&<>
      <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.6fr) minmax(280px,.8fr)',gap:18}}>
        <div style={card}><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start'}}><div><div style={{color:'#627d98',fontSize:13}}>Welcome back</div><h1 style={{fontSize:32,margin:'4px 0 10px'}}>{staff.preferred_name||staff.full_name}</h1><p style={{margin:0,color:'#627d98'}}>Your permanent BIMED ID is <strong>{staff.bimed_id}</strong>. Keep using this account throughout your employment.</p></div><div style={{width:92,height:92,borderRadius:'50%',overflow:'hidden',background:'#e6fffb',display:'grid',placeItems:'center',flexShrink:0}}>{staff.profile_photo_url?<img src={staff.profile_photo_url} alt='BIMED staff photograph' style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<span style={{fontWeight:900,color:'#0f766e',fontSize:28}}>{String(staff.full_name||'?').split(' ').map((x:string)=>x[0]).slice(0,2).join('')}</span>}</div></div></div>
        <div style={card}><div style={{color:'#627d98',fontSize:13}}>Profile readiness</div><div style={{fontSize:28,fontWeight:900,margin:'4px 0 12px'}}>{staff.pps_number?'Ready':'PPS number pending'}</div><div style={{height:8;background:'#edf2f7',borderRadius:8,overflow:'hidden'}}><div style={{height:'100%',width:staff.pps_number?'100%':'70%',background:'#0f766e'}}/></div><div style={{fontSize:12,color:'#627d98',marginTop:8}}>{staff.pps_number?'Irish payroll details have started.':'Add your PPS number when you receive it in Ireland.'}</div></div>
      </section>
      <section style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:18,marginTop:18}}>
       <div style={card}><div style={{fontSize:13,color:'#627d98'}}>Upcoming shifts</div><div style={{fontSize:30,fontWeight:900}}>{shifts.filter(s=>s.status!=='cancelled').length}</div><button onClick={()=>setTab('rota')} style={{border:0,background:'none',color:'#0f766e',fontWeight:800,padding:0}}>Open rota →</button></div>
       <div style={card}><div style={{fontSize:13,color:'#627d98'}}>Payslips available</div><div style={{fontSize:30,fontWeight:900}}>{payslips.length}</div><button onClick={()=>setTab('pay')} style={{border:0,background:'none',color:'#0f766e',fontWeight:800,padding:0}}>View payslips →</button></div>
       <div style={card}><div style={{fontSize:13,color:'#627d98'}}>Unread notifications</div><div style={{fontSize:30,fontWeight:900}}>{unread}</div><span style={{fontSize:12,color:'#627d98'}}>Rota, payroll, training and BIMED updates</span></div>
      </section>
    </>}
    {tab==='rota'&&<section style={{display:'grid',gridTemplateColumns:'1.5fr 1fr',gap:18}}><div style={card}><h2 style={{marginTop:0}}>My Rota</h2>{shifts.length===0?<p style={{color:'#627d98'}}>No assigned shifts yet.</p>:<div style={{display:'grid',gap:10}}>{shifts.map(s=><div key={s.id} style={{padding:14,border:'1px solid #e5eaf0',borderRadius:12,display:'flex',justifyContent:'space-between',gap:16}}><div><strong>{s.shift_type}</strong><div>{s.shift_date} · {new Date(s.start_at).toLocaleTimeString('en-IE',{hour:'2-digit',minute:'2-digit'})}–{new Date(s.end_at).toLocaleTimeString('en-IE',{hour:'2-digit',minute:'2-digit'})}</div><div style={{fontSize:12,color:'#627d98'}}>{s.location||'BIMED'}{s.role?` · ${s.role}`:''}</div></div><span style={{fontSize:12,fontWeight:800,color:s.status==='cancelled'?'#c53030':'#0f766e'}}>{s.status}</span></div>)}</div>}</div><div style={card}><h2 style={{marginTop:0}}>My Shift Requests</h2>{requests.length===0?<p style={{color:'#627d98'}}>No shift requests yet.</p>:requests.map(r=><div key={r.id} style={{padding:'12px 0',borderBottom:'1px solid #edf2f7'}}><strong>{r.request_type}</strong><div style={{fontSize:12,color:'#627d98'}}>{r.status}</div>{r.reason&&<div style={{fontSize:13,marginTop:4}}>{r.reason}</div>}</div>)}</div></section>}
    {tab==='pay'&&<section style={card}><h2 style={{marginTop:0}}>My Payslips</h2>{payslips.length===0?<p style={{color:'#627d98'}}>Your BIMED payslips will appear here when issued.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{textAlign:'left',padding:10}}>Pay period</th><th style={{textAlign:'right',padding:10}}>Gross</th><th style={{textAlign:'right',padding:10}}>Deductions</th><th style={{textAlign:'right',padding:10}}>Net pay</th></tr></thead><tbody>{payslips.map(p=><tr key={p.id} style={{borderTop:'1px solid #edf2f7'}}><td style={{padding:10}}>{p.pay_period_start} – {p.pay_period_end}</td><td style={{textAlign:'right',padding:10}}>€{Number(p.gross_pay||0).toFixed(2)}</td><td style={{textAlign:'right',padding:10}}>€{(Number(p.paye||0)+Number(p.prsi||0)+Number(p.usc||0)+Number(p.other_deductions||0)).toFixed(2)}</td><td style={{textAlign:'right',padding:10,fontWeight:900}}>€{Number(p.net_pay||0).toFixed(2)}</td></tr>)}</tbody></table></div>}</section>}
    {tab==='profile'&&<section style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 320px',gap:18}}><form onSubmit={saveProfile} style={card}><h2 style={{marginTop:0}}>My BIMED Profile</h2><div style={{display:'grid',gap:14}}><div><label style={{display:'block',fontWeight:800,fontSize:13}}>BIMED ID</label><div style={{padding:12,borderRadius:10,background:'#f4f7fb',fontWeight:900}}>{staff.bimed_id}</div></div><div><label style={{display:'block',fontWeight:800,fontSize:13}}>PPS Number</label><input value={pps} onChange={e=>setPps(e.target.value)} placeholder='Not yet available? Leave blank and add it later.' style={{width:'100%',padding:12,border:'1px solid #d9e2ec',borderRadius:10}}/><div style={{fontSize:12,color:'#627d98',marginTop:5}}>You do not need an Irish PPS Number before arrival. Add it when you receive it.</div></div><div><label style={{display:'block',fontWeight:800,fontSize:13}}>Phone</label><input value={phone} onChange={e=>setPhone(e.target.value)} style={{width:'100%',padding:12,border:'1px solid #d9e2ec',borderRadius:10}}/></div><div><label style={{display:'block',fontWeight:800,fontSize:13}}>Irish/Current Address</label><input value={address} onChange={e=>setAddress(e.target.value)} placeholder='Add your Ireland address when available' style={{width:'100%',padding:12,border:'1px solid #d9e2ec',borderRadius:10}}/></div><button disabled={busy} style={{padding:'12px 16px',border:0,borderRadius:10,background:'#0f766e',color:'#fff',fontWeight:900}}>{busy?'Saving…':'Save profile'}</button></div></form><div style={card}><h2 style={{marginTop:0}}>BIMED Staff Photograph</h2><div style={{width:180,height:220,borderRadius:14,overflow:'hidden',background:'#eef2f7',display:'grid',placeItems:'center',marginBottom:14}}>{staff.profile_photo_url?<img src={staff.profile_photo_url} alt='BIMED Staff Photograph' style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<span style={{color:'#829ab1'}}>No photo</span>}</div><input id='photo' type='file' accept='image/jpeg,image/png,image/webp' onChange={uploadPhoto} disabled={photoBusy}/><p style={{fontSize:12,color:'#627d98'}}>Use a recent clear photograph. Maximum 5 MB.</p></div></section>}
   </div>
 </main>
}
