'use client';

import { useEffect, useState } from 'react';

type Shift=Record<string,any>;type RequestRow=Record<string,any>;
export default function AdminRotaPage(){
 const [shifts,setShifts]=useState<Shift[]>([]);const [requests,setRequests]=useState<RequestRow[]>([]);const [error,setError]=useState('');const [date,setDate]=useState(new Date().toISOString().slice(0,10));
 async function load(){const r=await fetch(`/api/admin/rota?from=${date}&to=${date}`);const d=await r.json();if(r.status===401){setError('Admin session required.');return}if(!r.ok){setError(d.error||'Unable to load rota.');return}setShifts(d.shifts||[]);setRequests(d.pendingRequests||[])}useEffect(()=>{load()},[date]);
 async function approve(id:string,decision:'approve'|'decline'){const r=await fetch('/api/admin/rota',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'request_response',requestId:id,decision})});const d=await r.json();if(!r.ok){setError(d.error||'Unable to respond.');return}load()}
 async function createShift(){const shiftDate=prompt('Shift date (YYYY-MM-DD)',date);if(!shiftDate)return;const start=prompt('Start time (ISO timestamp or YYYY-MM-DDTHH:mm)',`${shiftDate}T07:00:00`);if(!start)return;const end=prompt('End time',`${shiftDate}T15:00:00`);if(!end)return;const type=prompt('Shift type','Early');if(!type)return;const r=await fetch('/api/admin/rota',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'create',shiftDate,startAt:start,endAt:end,shiftType:type})});const d=await r.json();if(!r.ok){setError(d.error||'Unable to create shift.');return}load()}
 return <main style={{padding:'32px 5vw',background:'#f7f9fc',minHeight:'100vh',fontFamily:'system-ui',color:'#102a43'}}><div style={{maxWidth:1300,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:22}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1.4,color:'#0f766e'}}>BIMED Healthcare</div><h1 style={{margin:'5px 0'}}>Rota Manager</h1><p style={{margin:0,color:'#627d98'}}>Create, assign and manage the permanent staff rota.</p></div><button onClick={createShift} style={{padding:'11px 15px',border:0,borderRadius:10,background:'#0f766e',color:'#fff',fontWeight:800}}>Create available shift</button></div>{error&&<div style={{background:'#fff5f5',color:'#9b2c2c',padding:12,borderRadius:10,marginBottom:15}}>{error}</div>}<div style={{marginBottom:18}}><label style={{fontWeight:800,fontSize:13}}>Rota date </label><input type='date' value={date} onChange={e=>setDate(e.target.value)} style={{padding:10,border:'1px solid #d9e2ec',borderRadius:9,marginLeft:8}}/></div><section style={{display:'grid',gridTemplateColumns:'1.5fr 1fr',gap:18}}><div style={{background:'#fff',border:'1px solid #e5eaf0',borderRadius:16,padding:18}}><h2 style={{marginTop:0}}>Shifts</h2>{shifts.length===0?<p style={{color:'#627d98'}}>No shifts for this date.</p>:<div style={{display:'grid',gap:10}}>{shifts.map(s=><div key={s.id} style={{border:'1px solid #e5eaf0',borderRadius:12,padding:13}}><div style={{display:'flex',justifyContent:'space-between'}}><strong>{s.shift_type}</strong><span style={{fontSize:12,fontWeight:800}}>{s.status}</span></div><div style={{marginTop:5}}>{new Date(s.start_at).toLocaleTimeString('en-IE',{hour:'2-digit',minute:'2-digit'})}–{new Date(s.end_at).toLocaleTimeString('en-IE',{hour:'2-digit',minute:'2-digit'})}</div><div style={{fontSize:12,color:'#627d98'}}>{s.location||'BIMED'} · {s.role||'Role not set'}</div><div style={{fontSize:13,fontWeight:800,marginTop:7}}>{s.staff?.bimed_id||'OPEN SHIFT'} {s.staff?.full_name?`· ${s.staff.full_name}`:''}</div></div>)}</div>}</div><div style={{background:'#fff',border:'1px solid #e5eaf0',borderRadius:16,padding:18}}><h2 style={{marginTop:0}}>Pending Requests</h2>{requests.length===0?<p style={{color:'#627d98'}}>No pending shift requests.</p>:requests.map(r=><div key={r.id} style={{padding:'12px 0',borderBottom:'1px solid #edf2f7'}}><strong>{r.staff?.bimed_id} · {r.staff?.full_name}</strong><div style={{fontSize:13}}>{r.request_type}</div><div style={{fontSize:12,color:'#627d98'}}>{r.shift?.shift_date} · {r.shift?.shift_type}</div><div style={{display:'flex',gap:8,marginTop:8}}><button onClick={()=>approve(r.id,'approve')} style={{padding:'7px 10px',border:0,borderRadius:8,background:'#0f766e',color:'#fff'}}>Approve</button><button onClick={()=>approve(r.id,'decline')} style={{padding:'7px 10px',border:'1px solid #d9e2ec',borderRadius:8,background:'#fff'}}>Decline</button></div></div>)}</div></section></div></main>
}
