'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { BIMED_ROLE_SALARIES, recruitmentRoleSlug } from '@/lib/bimed-role-policy';

type Row = Record<string, any>;
const card: React.CSSProperties = { background: '#fff', border: '1px solid #e5eaf0', borderRadius: 16, padding: 20, boxShadow: '0 8px 28px rgba(15,23,42,.04)' };
function dateTime(value?: string | null) { if (!value) return '—'; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : d.toLocaleString('en-IE'); }
function dateLabel(value?: string | null) { if (!value) return '—'; const d = new Date(`${value}T12:00:00`); return Number.isNaN(d.getTime()) ? value : d.toLocaleDateString('en-IE', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' }); }
function time(value?: string | null) { if (!value) return '—'; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : d.toLocaleTimeString('en-IE', { hour: '2-digit', minute: '2-digit' }); }

export default function AdminStaffDetailPage() {
  const params = useParams<{ id: string }>(); const router = useRouter();
  const [staff, setStaff] = useState<Row | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState<string | null>(null); const [status, setStatus] = useState(''); const [activationUrl, setActivationUrl] = useState(''); const [actionMessage, setActionMessage] = useState('');
  async function load() { setError(''); const response = await fetch(`/api/admin/staff/${params.id}`); const data = await response.json(); if (response.status === 401) { setError('Admin session required.'); return; } if (!response.ok) { setError(data.error || 'Unable to load staff member.'); return; } setStaff(data.staff); setStatus(data.staff.status || ''); }
  useEffect(() => { void load(); }, [params.id]);
  async function updateStatus() { setBusy('status'); setError(''); try { const response = await fetch('/api/admin/staff', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'status', staffId: params.id, status }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to update status.'); setStaff((current) => current ? { ...current, ...data.staff } : current); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update status.'); } finally { setBusy(null); } }
  async function portalAction(action: 'restrict_portal' | 'reactivate_portal') { setBusy(action); setError(''); setActionMessage(''); if (action === 'restrict_portal' && !window.confirm(`Restrict ${staff?.full_name || 'this recruit'} from the Staff Portal because the €4,000 accommodation contribution has not been paid? Their BIMED ID and full record will be retained and access can be reactivated later.`)) { setBusy(null); return; } try { const response = await fetch('/api/admin/staff', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action, staffId: params.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to update portal access.'); setStaff(data.staff); setStatus(data.staff.status || ''); setActionMessage(data.message || 'Saved.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update portal access.'); } finally { setBusy(null); } }
  async function rotateActivation() { setBusy('activation'); setError(''); setActionMessage(''); try { const response = await fetch('/api/admin/staff', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'rotate_activation', staffId: params.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to create activation link.'); setActivationUrl(data.activationUrl || ''); setActionMessage(data.message || 'A fresh activation link was generated and emailed to the recruitment email address.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create activation link.'); } finally { setBusy(null); } }
  async function copyActivation() { if (!activationUrl) return; try { await navigator.clipboard.writeText(activationUrl); } catch { setError('The activation link was created, but this browser would not copy it automatically.'); } }
  if (!staff) return <main style={{ padding: 40, fontFamily: 'system-ui' }}>{error || 'Loading staff record…'}</main>;
  const shifts: Row[] = staff.shifts || []; const attendance: Row[] = staff.attendance || []; const leaveRequests: Row[] = staff.leaveRequests || []; const payslips: Row[] = staff.payslips || []; const auditLog: Row[] = staff.auditLog || [];
  const upcomingShifts = shifts.filter((s) => new Date(s.start_at).getTime() > Date.now() && !['cancelled', 'completed'].includes(s.status)).length; const pendingLeave = leaveRequests.filter((leave) => leave.status === 'pending').length; const salary = BIMED_ROLE_SALARIES[recruitmentRoleSlug(staff.role) || 'support-worker']; const residentialAddress = staff.address_line_1 || [staff.address_line_2, staff.city, staff.county, staff.eircode, staff.country].filter(Boolean).join(', '); const restrictedForNonPayment = staff.application_id && staff.portal_restriction_reason === 'accommodation_nonpayment'; const restrictedForSponsorshipCancellation = staff.application_id && staff.portal_restriction_reason === 'sponsorship_cancellation';
  return <main style={{ minHeight: '100vh', background: '#f7f9fc', padding: '32px 5vw', fontFamily: 'system-ui', color: '#102a43' }}><div style={{ maxWidth: 1240, margin: '0 auto' }}>
    <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}><button onClick={() => router.push('/admin/staff')} style={secondaryButton}>← Workforce staff</button><button onClick={() => router.push('/admin/rota')} style={secondaryButton}>Open rota manager</button></div>
    {error && <div style={{ marginTop: 16, padding: 12, borderRadius: 10, background: '#fff5f5', color: '#9b2c2c', border: '1px solid #fed7d7' }}>{error}</div>}{actionMessage && <div style={{ marginTop: 16, padding: 12, borderRadius: 10, background: '#ecfdf5', color: '#166534', border: '1px solid #bbf7d0' }}>{actionMessage}</div>}
    <section style={{ ...card, marginTop: 18 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 20, alignItems: 'flex-start' }}><div><div style={{ fontSize: 12, fontWeight: 800, letterSpacing: 1.3, color: '#0f766e' }}>BIMED Healthcare</div><h1 style={{ margin: '4px 0' }}>{staff.preferred_name || staff.full_name}</h1><p style={{ margin: 0, color: '#627d98' }}>{staff.role || 'BIMED Staff'} · <strong>{staff.bimed_id}</strong></p><div style={{ marginTop: 12, display: 'flex', gap: 8, flexWrap: 'wrap' }}><span style={pill}>{staff.status}</span><span style={pill}>{staff.employment_type || 'Employment type pending'}</span>{staff.application_id && <span style={{ ...pill, background: '#e8f4ff', color: '#1d4ed8' }}>Recruitment linked</span>}</div></div><div style={{ width: 128, height: 160, overflow: 'hidden', borderRadius: 14, background: '#eef2f7', display: 'grid', placeItems: 'center' }}>{staff.profile_photo_url ? <img src={staff.profile_photo_url} alt='BIMED staff photograph' style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : <span style={{ color: '#829ab1' }}>No photograph</span>}</div></div></section>
    {(restrictedForNonPayment || restrictedForSponsorshipCancellation) && <section style={{ ...card, marginTop: 18, borderColor: restrictedForSponsorshipCancellation ? '#fecaca' : '#fed7aa', background: restrictedForSponsorshipCancellation ? '#fef2f2' : '#fff7ed' }}>
      <h2 style={{ marginTop: 0, color: restrictedForSponsorshipCancellation ? '#991b1b' : '#9a3412' }}>{restrictedForSponsorshipCancellation ? 'Sponsorship cancellation finalised' : 'Staff Portal access restricted'}</h2>
      <p style={{ color: restrictedForSponsorshipCancellation ? '#7f1d1d' : '#7c2d12', lineHeight: 1.65, marginBottom: 8 }}>{staff.portal_restriction_message}</p>
      <div style={{ fontSize: 12, color: restrictedForSponsorshipCancellation ? '#991b1b' : '#9a3412' }}>Restricted {dateTime(staff.portal_restricted_at)} by {staff.portal_restricted_by || 'BIMED admin'}</div>
      {restrictedForSponsorshipCancellation ? <div style={{ marginTop: 10, color: '#7f1d1d', fontSize: 13, lineHeight: 1.6 }}>The recruitment application has been withdrawn and the employment contract has been voided. This sponsorship-cancellation restriction is not a normal suspension and is not restorable from the Staff Portal controls.</div> : <button disabled={busy === 'reactivate_portal'} onClick={() => void portalAction('reactivate_portal')} style={{ ...primaryButton, marginTop: 14 }}>{busy === 'reactivate_portal' ? 'Reactivating…' : 'Reactivate Staff Portal access'}</button>}
    </section>}
    {staff.application_id && !restrictedForNonPayment && !restrictedForSponsorshipCancellation && staff.status !== 'suspended' && <section style={{ ...card, marginTop: 18, borderColor: '#fde68a', background: '#fffbeb' }}><h2 style={{ marginTop: 0, color: '#854d0e' }}>Overseas recruit portal control</h2><p style={{ color: '#78350f', lineHeight: 1.65 }}>This control is specifically for the post-contract accommodation contribution workflow. Restricting access preserves the recruit's permanent BIMED ID and records. It does not delete the underlying recruitment or employment history.</p><button disabled={busy === 'restrict_portal'} onClick={() => void portalAction('restrict_portal')} style={{ ...dangerButton }}>{busy === 'restrict_portal' ? 'Restricting…' : 'Restrict portal for €4,000 accommodation non-payment'}</button></section>}
    <section style={{ display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 12, marginTop: 18 }}><Metric label='Upcoming shifts' value={upcomingShifts} /><Metric label='Pending leave' value={pendingLeave} /><Metric label='Payslips' value={payslips.length} /></section>
    <section style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18, marginTop: 18 }}><div style={card}><h2 style={{ marginTop: 0 }}>Employment</h2><Info label='BIMED ID' value={staff.bimed_id} /><Info label='Status' value={staff.status} /><Info label='Role' value={staff.role} /><Info label='Agreed annual salary' value={salary || 'Not configured'} /><Info label='Department' value={staff.department} /><Info label='Employment type' value={staff.employment_type} /><Info label='Start date' value={staff.employment_start_date} /><Info label='Primary location' value={staff.primary_location} /></div><div style={card}><h2 style={{ marginTop: 0 }}>Employee residential details</h2><Info label='Address' value={residentialAddress} /><Info label='Phone' value={staff.phone} /><Info label='Email' value={staff.email} /><Info label='Date of birth' value={staff.date_of_birth} /><Info label='Nationality' value={staff.nationality} /></div></section>
    <section style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18, marginTop: 18 }}><div style={card}><h2 style={{ marginTop: 0 }}>Payroll / Irish details</h2><Info label='PPS number' value={staff.pps_number || 'Pending'} /><Info label='PPS status' value={staff.pps_status || 'pending'} /><Info label='Tax status' value={staff.tax_status || 'pending'} /><Info label='Revenue reference' value={staff.revenue_reference || 'Not provided'} /><Info label='IBAN' value={staff.iban || 'Not provided'} /><Info label='BIC' value={staff.bic || 'Not provided'} /><Info label='Bank' value={staff.bank_name || 'Not provided'} /></div></section>
    <section style={{ ...card, marginTop: 18 }}><h2 style={{ marginTop: 0 }}>Account activation</h2><p style={{ color: '#627d98' }}>Generate a fresh seven-day activation link without exposing passwords or session credentials in the admin UI.</p><div style={{ display: 'flex', gap: 9, flexWrap: 'wrap' }}><button disabled={busy === 'activation'} onClick={() => void rotateActivation()} style={primaryButton}>{busy === 'activation' ? 'Generating…' : 'Generate activation link'}</button>{activationUrl && <button onClick={() => void copyActivation()} style={secondaryButton}>Copy activation link</button>}</div>{activationUrl && <textarea readOnly value={activationUrl} rows={3} style={{ width: '100%', marginTop: 12, padding: 10, border: '1px solid #d9e2ec', borderRadius: 9, boxSizing: 'border-box' }} />}</section>
    <section style={{ ...card, marginTop: 18 }}><h2 style={{ marginTop: 0 }}>Manage staff status</h2><div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}><select value={status} onChange={(e) => setStatus(e.target.value)} style={{ padding: 11, border: '1px solid #d9e2ec', borderRadius: 9 }}><option value='pre_arrival'>Pre-arrival</option><option value='active'>Active</option><option value='on_leave'>On leave</option><option value='suspended'>Suspended</option><option value='former'>Former</option></select><button disabled={busy === 'status'} onClick={() => void updateStatus()} style={primaryButton}>{busy === 'status' ? 'Saving…' : 'Save status'}</button></div></section>
    <section style={{ ...card, marginTop: 18 }}><h2 style={{ marginTop: 0 }}>Recent rota</h2>{shifts.length === 0 ? <p style={{ color: '#627d98' }}>No shifts recorded.</p> : <div style={{ display: 'grid', gap: 8 }}>{shifts.map((shift) => <div key={shift.id} style={row}><div><strong>{shift.shift_type}</strong><div style={{ fontSize: 13 }}>{dateLabel(shift.shift_date)} · {time(shift.start_at)}–{time(shift.end_at)}</div><div style={{ fontSize: 12, color: '#627d98' }}>{shift.location || 'BIMED'}{shift.role ? ` · ${shift.role}` : ''}</div></div><span style={statusText}>{shift.status}</span></div>)}</div>}</section>
    <section style={{ ...card, marginTop: 18 }}><h2 style={{ marginTop: 0 }}>Time & attendance</h2>{attendance.length === 0 ? <p style={{ color: '#627d98' }}>No attendance records recorded.</p> : <div style={{ display: 'grid', gap: 8 }}>{attendance.map((entry) => <div key={entry.id} style={row}><div><strong>{entry.shift?.shift_type || 'Shift'}</strong><div style={{ fontSize: 13 }}>{dateLabel(entry.shift?.shift_date)} · {time(entry.clock_in_at)}–{time(entry.clock_out_at)}</div><div style={{ fontSize: 12, color: '#627d98' }}>{entry.shift?.location || 'BIMED'}{entry.shift?.role ? ` · ${entry.shift.role}` : ''} · Break {entry.break_minutes || 0}m</div>{entry.notes && <div style={{ fontSize: 12, color: '#627d98', marginTop: 3 }}>{entry.notes}</div>}</div><span style={statusText}>{entry.status}</span></div>)}</div>}</section>
    <section style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18, marginTop: 18 }}><div style={card}><h2 style={{ marginTop: 0 }}>Leave history</h2>{leaveRequests.length === 0 ? <p style={{ color: '#627d98' }}>No leave requests recorded.</p> : leaveRequests.map((leave) => <div key={leave.id} style={row}><div><strong>{leave.leave_type}</strong><div style={{ fontSize: 13 }}>{dateLabel(leave.start_date)} → {dateLabel(leave.end_date)}</div>{leave.reason && <div style={{ fontSize: 12, color: '#627d98' }}>{leave.reason}</div>}</div><span style={statusText}>{leave.status}</span></div>)}</div><div style={card}><h2 style={{ marginTop: 0 }}>Payslips</h2>{payslips.length === 0 ? <p style={{ color: '#627d98' }}>No payslips issued.</p> : payslips.map((slip) => <div key={slip.id} style={row}><div><strong>{dateLabel(slip.period_start)} → {dateLabel(slip.period_end)}</strong><div style={{ fontSize: 13 }}>Gross €{Number(slip.gross_pay || 0).toFixed(2)} · Net €{Number(slip.net_pay || 0).toFixed(2)}</div><div style={{ fontSize: 12, color: '#627d98' }}>Issued {dateTime(slip.issued_at)}</div></div><span style={statusText}>{slip.status || 'issued'}</span></div>)}</div></section>
    <section style={{ ...card, marginTop: 18, marginBottom: 30 }}><h2 style={{ marginTop: 0 }}>Audit trail</h2>{auditLog.length === 0 ? <p style={{ color: '#627d98' }}>No staff audit entries yet.</p> : auditLog.map((entry) => <div key={entry.id} style={row}><div><strong>{entry.event_type}</strong><div style={{ fontSize: 12, color: '#627d98' }}>{dateTime(entry.created_at)} · {entry.actor || 'system'}</div></div><span style={{ fontSize: 12, color: '#627d98' }}>{entry.metadata ? JSON.stringify(entry.metadata) : ''}</span></div>)}</section>
  </div></main>;
}
const primaryButton: React.CSSProperties = { padding: '10px 14px', border: 0, borderRadius: 9, background: '#0f766e', color: '#fff', fontWeight: 800 }; const secondaryButton: React.CSSProperties = { padding: '10px 14px', border: '1px solid #d9e2ec', borderRadius: 9, background: '#fff', fontWeight: 700 }; const dangerButton: React.CSSProperties = { padding: '11px 14px', border: 0, borderRadius: 9, background: '#b42318', color: '#fff', fontWeight: 900 }; const pill: React.CSSProperties = { padding: '5px 9px', borderRadius: 999, background: '#e6fffa', color: '#0f766e', fontSize: 12, fontWeight: 800 }; const row: React.CSSProperties = { padding: '11px 0', borderBottom: '1px solid #edf2f7', display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'flex-start' }; const statusText: React.CSSProperties = { fontSize: 12, fontWeight: 800, whiteSpace: 'nowrap' };
function Metric({ label, value }: { label: string; value: number }) { return <div style={card}><div style={{ fontSize: 12, color: '#627d98' }}>{label}</div><div style={{ fontSize: 28, fontWeight: 900, marginTop: 4 }}>{value}</div></div>; }
function Info({ label, value }: { label: string; value: unknown }) { return <div style={{ padding: '8px 0', borderBottom: '1px solid #edf2f7' }}><div style={{ fontSize: 12, color: '#627d98' }}>{label}</div><div style={{ fontWeight: 700 }}>{String(value || '—')}</div></div>; }
