-- Overseas staff permit journey and accommodation arrangement.
-- This records the workflow and evidence without representing a permit/visa approval guarantee.
create table if not exists recruitment_staff_permit_cases (
  id uuid primary key default gen_random_uuid(),
  staff_id uuid not null unique references recruitment_staff(id) on delete cascade,
  pathway text not null default 'employment_permit_sponsorship',
  status text not null default 'not_started',
  requested_at timestamptz,
  admin_reviewed_at timestamptz,
  permit_type text,
  permit_application_id text,
  permit_submitted_at timestamptz,
  permit_decision text,
  permit_decision_at timestamptz,
  permit_refusal_reason text,
  visa_status text,
  visa_application_reference text,
  visa_submitted_at timestamptz,
  visa_decision text,
  visa_decision_at timestamptz,
  visa_refusal_reason text,
  accommodation_offered boolean not null default false,
  accommodation_period_months integer,
  accommodation_amount_eur numeric(12,2),
  accommodation_currency text not null default 'EUR',
  accommodation_start_date date,
  accommodation_end_date date,
  accommodation_agreement_path text,
  accommodation_payment_status text not null default 'not_due',
  accommodation_paid_at timestamptz,
  accommodation_refund_status text not null default 'not_due',
  accommodation_refund_amount_eur numeric(12,2),
  accommodation_refund_started_at timestamptz,
  accommodation_refund_completed_at timestamptz,
  accommodation_refund_installments integer not null default 4,
  accommodation_refund_installments_paid integer not null default 0,
  work_authorised boolean not null default false,
  shift_eligibility text not null default 'blocked',
  supporting_documents jsonb not null default '{}'::jsonb,
  admin_packet jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('not_started','requested','admin_review','permit_preparation','permit_submitted','permit_granted','permit_refused','visa_preparation','visa_submitted','visa_granted','visa_refused','arrived','closed')),
  check (accommodation_period_months is null or accommodation_period_months > 0),
  check (accommodation_amount_eur is null or accommodation_amount_eur >= 0),
  check (accommodation_refund_installments > 0),
  check (accommodation_refund_installments_paid >= 0 and accommodation_refund_installments_paid <= accommodation_refund_installments),
  check (shift_eligibility in ('blocked','eligible'))
);
create index if not exists recruitment_staff_permit_cases_status_idx on recruitment_staff_permit_cases(status);
create index if not exists recruitment_staff_permit_cases_refund_idx on recruitment_staff_permit_cases(accommodation_refund_status);
alter table recruitment_staff_permit_cases enable row level security;
revoke all on recruitment_staff_permit_cases from anon, authenticated;
